### ISSUE TITLE
colab errors

### ISSUE THREAD

**Issue by molo32** [IIGROUP/TediGAN#11]
!python demo.py --description='he is a young woman' --mode='woman' --step=500 --f_oom=False

```
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    from idinvert_pytorch.models.perceptual_model import PerceptualModel
ModuleNotFoundError: No module named 'idinvert_pytorch.models.perceptual_model'

```

![problem tedigan](https://user-images.githubusercontent.com/55426197/115800153-680a2900-a3b0-11eb-8fe7-258627e23fad.png)

**Comment by molo32** [comment]
I restart the notebook again and I get:

![problem tedigan2](https://user-images.githubusercontent.com/55426197/115802301-03050200-a3b5-11eb-841f-96029623ffd2.png)

**Comment by weihaox** [comment]
Fixed in #https://github.com/IIGROUP/TediGAN/commit/31982c119a57eaa32fdadd0948f8865ff4e44f2f. Please try again.
