### ISSUE TITLE
instance-level optimization

### ISSUE THREAD

**Issue by baopmessi** [IIGROUP/TediGAN#12]
Great paper! Sorry for my english. Can you explain why (5) formula help identity preservation. I also ask some in (5)
 - initialization z is inverted latent code of mixing text and visual latent code ?
 - x is origin visual input image ?
 - 2 first terms help preserve pixel and semantic and last term help regularize the latent is in region visual encoder work.
![image](https://user-images.githubusercontent.com/34626618/115940517-135bd080-a4cc-11eb-93da-e90e71208e1f.png)

**Comment by weihaox** [comment]
Your explanations of Equation (5) are correct. This optimization can be performed after either the inversion or the style mixing. If optimizing the mixed latent code of text and image (ie using it in the final step), the manipulated regions may 'change back' as in the original image. Thus, regarding the optimization as part of the inversion module in the testing phase is a better choice.

If you want to preserve identity (especially for the "mixed" latent codes), my suggestion is to use a dedicated [face recognition loss](https://github.com/eladrich/pixel2style2pixel/blob/master/criteria/id_loss.py) based on ArcFace to replace (5) as the instance-level optimization.

About how it works, the following results are helpful to explain. Roughly speaking, the identity is preserved by pixel and semantic reconstruction.

<img width="566" alt="截屏2021-04-24 上午11 15 08" src="https://user-images.githubusercontent.com/54136324/115945434-6777ac80-a4ee-11eb-85e2-b28355a088c5.png">

(a) original image; (b) inversion result of [pSp](https://github.com/eladrich/pixel2style2pixel/); (c) inversion result of image encoder (d) inversion results after optimization.

**Comment by baopmessi** [comment]
Thanks you so much for your help !.
About instance-level optimization for text-guild image problem. I wonder are you restrict number of iteration optimization or something? Because in my intuition . If optimize equation (5)  then latent z* will is invert code of origin visually image. and irrelevant text or mix style of latent ( goal). Thanks you again if you can explain.

**Comment by weihaox** [comment]
Such instance-level optimization is not used since there is no original image. 

The number of iteration depends on different cases but 100 is good enough for identity preservation if it's conducted after the inversion module.

**Comment by baopmessi** [comment]
In figure 2:
"We then perform style mixing for target layers and get the target latent code wt. The final wt∗is obtained through instance-level optimization"
![image](https://user-images.githubusercontent.com/34626618/115947885-e1129900-a4f4-11eb-9bd9-e9e04d40904c.png)

**Comment by weihaox** [comment]
Yes, with enough iterations, the obtained latent code will be close to the original one, which means the manipulated image would be the same as the given image. If the instance-level optimization is performed as the final step, the number of iteration is important and you have to choose it carefully.

**Comment by baopmessi** [comment]
i got it. thanks you so much
