### ISSUE TITLE
inverted_codes.pt not exists

### ISSUE THREAD

**Issue by juneleung** [IIGROUP/TediGAN#13]
Hi, I try to run some high-res result by 
```
python demo.py --description='he is old' 
	--mode='man' --f_oom=False                           # set as True if OOM error.
	--step=500   --loss_clip_weight=200 
```
but I get error as cant find the pt: `FileNotFoundError: [Errno 2] No such file or directory: 'experiment/inference_results/inverted_codes.pt'`

Where can I download or generate this `inverted_codes.pt`? Thanks!

**Comment by weihaox** [comment]
Hi, @juneleung Thank you for the interest of our work.

For manipulation, `inverted_codes.pt` is the inverted codes of the given image. If you want to manipulate an image, you can obtained the `inverted_codes.pt` by running
```
python inference.py --exp_dir=experiment                # path of logs and results 
--checkpoint_path=pretrained_models/psp_ffhq_encode.pt  # path of pretrained models 
--data_path=experiment/images/img
```

For generation, it is randomly sampled. The picture you illustrated above is the results of generation. I use the same randomly-sampled latent codes. You can obtain such codes by running 
```
python demo.py --mode='gen' --step=1 
```
and move the `inverted_codes.pt` to path `'experiment/inference_results` (You can also assign the path using `--latent_path`). Then run 
```
python demo.py --description={$text} --mode='man' --f_oom=true  --step={$step} --loss_clip_weight={$weight}
```
To get good results, you may try different paramaters (all related paramaters are shown as following). In most cases, you should merely change the `loss_clip_weight` and `step`. 


```
parser.add_argument("--lr", type=float, default=0.1)
parser.add_argument("--step", type=int, default=200,
                    help="number of optimization steps")
parser.add_argument("--loss_pix_weight", type=float, default=1.0,
                    help='The pixel reconstruction loss scale for optimization. (default: 1.0)')
parser.add_argument("--loss_reg_weight", type=float, default=2.0,
                    help='The latent loss scale for optimization. (default: 2.0)')
parser.add_argument('--loss_feat_weight', type=float, default=5e-5,
                    help='The perceptual loss scale for optimization. (default: 5e-5)')
parser.add_argument('--loss_clip_weight', type=float, default=1,
                    help='The clip loss for optimization. (default: 2.0)')
parser.add_argument("--latent_path", type=str, default='experiment/inference_results/inverted_codes.pt',
                      help="starts the optimization from the given latent code. Expects a .pt format")
```
From my experience, if the desired attributes are global (*e.g.* hairstyle) or rarely appear in the CelebA and FFHQ dataset, it would be better if using large loss_clip_weight and more steps. 
For example, if the attributes you want to change is the expression, you may directly obtain pleasing results using the default setting. If it comes to hairstyle, you may try several times to get good results.

I have shared some [codes.zip](https://github.com/IIGROUP/TediGAN/files/6445643/codes.zip) I used in my experiments. You can try these if you want.

```
python demo.py --description={$text} --mode='man' --f_oom=true  --step={$step} --loss_clip_weight={$weight} --latent_path={$path}
```

**Comment by juneleung** [comment]
Thanks!

**Comment by qo4on** [comment]
The result does not look like "wearing eyeglasses". Could anyone tell me what I'm doing wrong? I do the following in Colab:
```
!python inference.py \
    --exp_dir=experiment \
    --checkpoint_path=pretrained_models/psp_ffhq_encode.pt \
    --data_path=experiment/images/img

!python demo.py \
    --description='He is wearing eyeglasses.' \
    --mode='man' \
    --step=500 \
    --f_oom=False

import cv2
from google.colab.patches import cv2_imshow

result = cv2.imread('/content/TediGAN/ext/experiment/final_result.png')
cv2_imshow(result)
```
![image](https://user-images.githubusercontent.com/35609308/139864574-6a921b97-d4cb-46e0-84b8-284703ac02ba.png)

**Comment by weihaox** [comment]
Our methods requires optimization, which means you might need adjust the layers for mixing or change the loss weights for satisfactory results. Besides, some attrubutes are more diffucult to manipulate than others such as necklace, hat, and eyeglasses. Starting from an easy attribute (e.g. smiling, expression) might be helpful to understand this process. For more discussions about how to change the weights, please refer to #5, #14, #9.
