### ISSUE TITLE
where is the code for training and testing the text encoder?

### ISSUE THREAD

**Issue by wty-ustc** [IIGROUP/TediGAN#15]
Congratulations！That's a nice work!
I've skimmed through your code, most of it comes from psp(cvpr2021) and idivert(eccv2020), so I'd like to know where is your main contribution code, i.e., code for training and testing the text encoder.

**Comment by weihaox** [comment]
The codes are not uploaded. Please stay tuned if you are interested.

**Comment by wty-ustc** [comment]
Thank you!



---Original---
From: ***@***.***&gt;
Date: Thu, May 20, 2021 11:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IIGROUP/TediGAN] where is the code for training and testing the text encoder? (#15)




 
The codes are not uploaded. Please stay tuned if you are interested.
