### ISSUE TITLE
How to evaluate the results?

### ISSUE THREAD

**Issue by cookie-ke** [IIGROUP/TediGAN#16]
The dataset is divided by .pickle file and how can I put them into the fold and use the fid or lpips to earn the result?
![image](https://user-images.githubusercontent.com/56613566/121795141-676b7180-cc40-11eb-9393-152461252113.png)

**Comment by weihaox** [comment]
The pickle files in the two folder `train` and `test` contain **names of images** for training and testing. If you load them using Python, you can see the `captions.pickle` in `training` contains 24000 images from `0.jpg` to `23999.jpg`. 

For the usage of FID and LPIPS, please refer to their repositories or explainations of some blogs. The values may be different using different generated images.

**Comment by cookie-ke** [comment]
What code I can use to divide the all images data to test data and train data ? It seems that If I want to use FID and LPIPS to evaluate the results,I need to have the original test image folder. I don’t know how to extract them to a new folder and I don’t find a blog tell me how to do that.

**Comment by weihaox** [comment]
> What code I can use to divide the all images data to test data and train data ?

You can manually move them into train and test folders. The training images are from 0 to 23000 and the rest are for testing. You have already had the images.

For FID and LPIPS calculations, please put the original testing images and the generated ones into corresponding folders. You don't have to use all the testing images if you just want to know how to run the evaluation. You could just use a few samples to see how it works.

**Comment by diamond0910** [comment]
How many generated images  do you use for FID? And the FID is calculated between these images and the testing dataset or the whole dataset?
