### ISSUE TITLE
Is training code available for new data?

### ISSUE THREAD

**Issue by tearscoco** [IIGROUP/TediGAN#19]
Hi, great work there!!

I am wondering if there's training code available where I can try on my own data instead of faces?

**Comment by weihaox** [comment]
You can use the scripts from genforce or pSp to train an image encoder (as described in the readme) on your data. Notice that in the current version, we use CLIP for text guidances and the codes for text encoder are not available for now. When trained the desired image encoder, you can change the path of such checkpoint and reload it for generation or manipulation. You can also refer to [StyleClip](https://github.com/orpatashnik/StyleCLIP), where multiple datasets are used.
