### ISSUE TITLE
what is the epoch you set for comparison methods that mentioned in your paper when you retrain them on the Multi-Modal CelebA-HQ dataset?

### ISSUE THREAD

**Issue by ourpubliccodes** [IIGROUP/TediGAN#36]
"All methods are retrained with the default settings on the proposed Multi-Modal CelebA-HQ dataset." in your paper.
So what is the epoch you set for each of these methods?

**Comment by weihaox** [comment]
The default settings (including the training epochs) in these methods' code repositories. For specific experimental settings, please refer to their respective code repositories.
