### ISSUE TITLE
Can you upload the train_vls.py

### ISSUE THREAD

**Issue by cripac-sjx** [IIGROUP/TediGAN#7]

**Comment by srinivaspavan9** [comment]
> _No description provided._

Can you upload what?

**Comment by cripac-sjx** [comment]
> > _No description provided._
> 
> Can you upload the "train_vls.py" file, thanks a lot.

**Comment by weihaox** [comment]
Thank you for the concern of our work.

I have some deadlines recently. I will start to organize the code when I am available. Notice that in the last commits, we extended our method to support image editing using StyleGAN and a pretrained language model CLIP, which frees us from training another text encoder.
