### ISSUE TITLE
How to use this with stylegan ADA

### ISSUE THREAD

**Issue by TheodoreGalanos** [IIGROUP/TediGAN#8]
Hello!

Thanks for sharing your work, really interesting!

I was curious if you could offer a small write up, or advice, on how to use this approach with a stylegan-ada model. You mention briefly that we could project the image into the space, which is something used in other guiding approaches, but how can that happen within this code?

Thank you so much!

**Comment by weihaox** [comment]
Thank you for the concerns of our work. 

The key idea of our method is the use of the pretrained stylegan. Our method includes three steps: stylegan training, stylegan inversion, and visual-linguistic learning.  `stylegan` here could be StyleGAN, StyleGAN2, or StyleGAN-Ada. 

For stylegan training, in most cases, you don't have to trained a stylegan model yourself and could simply use the official checkpoints. 

The goal of stylegan inversion is to get the latent codes of given images. There are three kinds of methods for this, you can refer to our GAN inversion [survry](https://arxiv.org/abs/2101.05278) and a curated [list](https://github.com/weihaox/awesome-gan-inversion) of inversion papers if interested. We choose to train an image encoder to map images into the latent space of stylegan in the paper. But actually, you could use any other methods to do this, _eg_, [`projector.py`](https://github.com/NVlabs/stylegan2-ada/blob/main/projector.py) provided by the official stylegan-ada repo.  If you want to train your own encoder, you can refer to [idinvert](https://github.com/genforce/idinvert_pytorch) or other gan inversion method. 

Once you could obtain the inverted latent codes for given images, you can train the visual-linguistic similarity. In the last commits, we extended our method to support image editing using StyleGAN and a pretrained language model [CLIP](https://github.com/openai/CLIP), which frees us from training another text encoder.
