### ISSUE TITLE
Unable to get accurate results while generating images.

### ISSUE THREAD

**Issue by ozamanan** [IIGROUP/TediGAN#9]
When I switch to "gen" mode and give even a simple text like "This is an old man", I do not get appropriate results.

**Comment by weihaox** [comment]
There are some possible reasons for your inappropriate results.

1. The difference between the two modes `man` and `gen` is that the former uses the inverted codes of real images while the latter uses the randomly sampled. It would be difficult for optimization if the given descriptions are significantly different from the images corresponding to these randomly sampled codes. 
2. The optimization is sometimes image-specific. We need to choose different parameters for some cases. 

My suggestion is to save these randomly sampled codes as .npy, reload them in the `man` mode, and try different parameters.   

Below is my parameters and results:
`python demo.py --description='This is an old man' --mode='gen' --f_oom=True --step=100  --loss_clip_weight=200`
The left image corresponds to the randomly sampled code and the right is the generation.
![final_result](https://user-images.githubusercontent.com/54136324/114969508-1858c880-9eab-11eb-97f5-5c3aa53e0dc2.png)

**Comment by weihaox** [comment]
Please close the issue if no other comments, thanks.
